### ISSUE TITLE
Веб-разработка

### ISSUE THREAD

**Issue by doomscar** [vectree/resources#45]
Пункт "Подготовка" => "Мотивация"
Женщина, которая изучила программирование и нашла работ(У) за 5 месяцев;
В третьем пункте стоит добавить ; как и в остальных.
Четвертый пункт, статья удалена.

**Comment by vladthelittleone** [comment]
@doomscar спасибо.

**Comment by vladthelittleone** [comment]
@doomscar поправил, в ближайшее время выкатим обновление
