### ISSUE TITLE
Проблема c данными в профиле: сылкa на github, "ИМЯ ПОЛЬЗОВАТЕЛЯ"

### ISSUE THREAD

**Issue by kononovit** [vectree/resources#61]
При смене "username" в профиле github, не происходит сменны  поля "username" в существующей ссылке на github в профиле, также остаётся статично "ИМЯ ПОЛЬЗОВАТЕЛЯ".
Т.е. при смене "username" в профиле github, при попытке получить доступ к github, получаем битую ссылку.
Может предусмотреть возможность установки имени пользователя?

**Comment by vladthelittleone** [comment]
@kononovit Добрый день. По идее username должен быть disabled. Не могли бы вы скинуть скрин?

**Comment by kononovit** [comment]
Уточню. Я прошел аутентификацию на vectree через гитхаб, потом поменял на гитхабе юзернейм, при это аутентификация на vectree проходит, но обновленние данных юзернейма и ссылки на гитхаб в профиле vectree не произошло.
![2](https://user-images.githubusercontent.com/46027009/67154330-007aa580-f303-11e9-96a8-49e39c01e6f6.png)

**Comment by vladthelittleone** [comment]
@kononovit спасибо, сегодня поправлю

**Comment by vladthelittleone** [comment]
@kononovit Готово, проверьте, пожалуйста
