### ISSUE TITLE
Не отображается иконка Linkedin в профиле.

### ISSUE THREAD

**Issue by kononovit** [vectree/resources#62]
При добавлении ссылки на Linkedin в профиле, не отображается иконка ссылки на Linkein профиль.

**Comment by vladthelittleone** [comment]
@kononovit спасибо, завтра проверю.

**Comment by kononovit** [comment]
![1](https://user-images.githubusercontent.com/46027009/67154347-2a33cc80-f303-11e9-9d60-59ef3bc8b4bc.png)

**Comment by kononovit** [comment]
![1](https://user-images.githubusercontent.com/46027009/67154360-7979fd00-f303-11e9-8a2b-82a953859e18.png)

**Comment by vladthelittleone** [comment]
@kononovit понял, спасибо.

**Comment by vladthelittleone** [comment]
@kononovit Готово, проверьте, пожалуйста
