### ISSUE TITLE
Ширина основного контента и выравнивание

### ISSUE THREAD

**Issue by kononovit** [vectree/resources#64]
Может стоит предусмотреть максимальную ширину контента и выравнивание? Чтение происхдит гораздо легче и можно бегло пробегать по тексту.
Пример в скриншоте:
![ширина текста](https://user-images.githubusercontent.com/46027009/67463959-1c57b180-f64b-11e9-8054-fb8e15414f83.png)
![Ширина текста 2](https://user-images.githubusercontent.com/46027009/67463969-211c6580-f64b-11e9-831e-f50dc38f3866.png)

**Comment by vladthelittleone** [comment]
@kononovit добрый день. видно я поставил fluid. изначально было ограничение

**Comment by vladthelittleone** [comment]
@kononovit выложил, проверьте.
