### ISSUE TITLE
Смещение элемента формы в профиле при ширине экрана больше 1318px

### ISSUE THREAD

**Issue by kononovit** [vectree/resources#65]
Браузер: | Mozilla Firefox
-- | --
Версия: | 69.0
Useragent: | Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
Размер окна браузера: | 1354x642 px
JavaScript: | Да
![верстка1](https://user-images.githubusercontent.com/46027009/67465656-3c3ca480-f64e-11e9-80f7-344528b6f951.png)
![верстка2](https://user-images.githubusercontent.com/46027009/67465674-43fc4900-f64e-11e9-90be-a234ea8ac3c2.png)

**Comment by vladthelittleone** [comment]
@kononovit сегодня проверю. спасибо.

**Comment by kononovit** [comment]
Что-то подобное наблюдается в Chrome в районе ширины экрана около 1135px.

**Comment by vladthelittleone** [comment]
@kononovit после фикса баги с fluid не смог воспроизвести

**Comment by vladthelittleone** [comment]
@kononovit выложил, проверьте пожалуйста.
