### ISSUE TITLE
Битая ссылка на чат

### ISSUE THREAD

**Issue by lup-** [vectree/resources#67]
В карточке команды https://vectree.ru/teams/40
![Screenshot_2019-11-05-21-56-41-540_com android chrome](https://user-images.githubusercontent.com/2142348/68237169-af172980-0017-11ea-896b-05c177c07047.png)

Ссылка на чат ведёт на https://vectree.ru/chat/undefined

**Comment by vladthelittleone** [comment]
@lup- как давно вы создали команду? если давно, то на тот момент еще не было функционала чата, поэтому он не был создан.

**Comment by lup-** [comment]
@vladthelittleone твоя правда. Я подключился к старой команде. Может быть имеет смысл в таком случае блокировать кнопку?

**Comment by vladthelittleone** [comment]
@lup- да, задисейблю кнопку. спасибо.

**Comment by vladthelittleone** [comment]
Закрываю таску на репо.
