### ISSUE TITLE
Битая ссылка в https://vectree.ru/text/80/1/0?pathId=78

### ISSUE THREAD

**Issue by stivo32** [vectree/resources#71]
Не до конца понял, где на гитхабе лежит аналогичная статья. 
https://github.com/vectree/resources/blob/master/text/00115.md имеет некоторые отличия.
В общем в векторе Объекты и конструктор https://vectree.ru/text/80/1/0?pathId=78 в секции "Прототип" есть ссылка "несколько замечательных статьей от learn.javascript", и она видимо не прописана, хотя подразумевается. При этом в статье на гитхабе данная ссылка вообще отсутствует и прописана плейн текстом. 
Ну и по ходу дела, статьей необходимо поправить на статей.

**Comment by vladthelittleone** [comment]
@stivo32 добрый день. спасибо за информацию. в ближайшее время поправлю!

**Comment by vladthelittleone** [comment]
@stivo32 готово! спасибо.
