### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by Alex-fire** [vectree/resources#81]
На странице https://vectree.ru/text/22/0/0?pathId=47 в предложении "И конечно захотите капнуть еще глубже." кОпнуть через "О" и слово "конечно" здесь выделяется с двух сторон запятыми.

**Comment by vladthelittleone** [comment]
@Alex-fire спасибо

**Comment by Alex-fire** [comment]
> @Alex-fire спасибо
:-)
