### ISSUE TITLE
Удален канал с видео

### ISSUE THREAD

**Issue by Alex-fire** [vectree/resources#82]
На странице https://vectree.ru/digest/14/0/0 ссылка на канал Романа Бровко. Канал удален :-(
Могу предложить на эту тему курс Наиля Алишева по Spring - https://www.youtube.com/watch?v=5ePo08sqcpk&list=PLAma_mKffTOR5o0WNHnY0mTjKxnCgSXrZ. Очень доходчиво объясняет.

**Comment by vladthelittleone** [comment]
@Alex-fire спасибо, поправил :)

**Comment by Alex-fire** [comment]
> @Alex-fire спасибо, поправил :)

Вам спасибо за ресурс :-)
